from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from xania.runtime.spa import SpaApp, _js_string


@dataclass(frozen=True)
class SpaCompiler:
    """
    Compile a `SpaApp` into:
    - `index.html`
    - `static/spa_runtime.js` (copied from package)
    - `static/app.js` (generated from Python spec)
    """

    title: str = "Xania SPA"
    tailwind: bool = True

    def write(self, app: SpaApp, out_dir: Path) -> None:
        out_dir = out_dir.resolve()
        static_dir = out_dir / "static"
        static_dir.mkdir(parents=True, exist_ok=True)

        self._write_index(out_dir, title=self.title, tailwind=self.tailwind)
        self._copy_spa_runtime(static_dir / "spa_runtime.js")
        (static_dir / "app.js").write_text(self._generate_app_js(app), encoding="utf-8")

    def _write_index(self, out_dir: Path, *, title: str, tailwind: bool) -> None:
        tw = '    <script src="https://cdn.tailwindcss.com"></script>\n' if tailwind else ""
        html = f"""<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{title}</title>
{tw}  </head>
  <body class="bg-gray-950 text-white">
    <div id="app"></div>
    <script src="/static/spa_runtime.js"></script>
    <script src="/static/app.js"></script>
  </body>
</html>
"""
        (out_dir / "index.html").write_text(html, encoding="utf-8")

    def _copy_spa_runtime(self, dest: Path) -> None:
        from importlib.resources import as_file, files

        src = files("xania").joinpath("static").joinpath("spa_runtime.js")
        with as_file(src) as src_path:
            dest.write_text(Path(src_path).read_text(encoding="utf-8"), encoding="utf-8")

    def _generate_app_js(self, app: SpaApp) -> str:
        lines: list[str] = []
        lines.append("// Generated by xania.runtime.SpaCompiler")
        lines.append("(function () {")
        lines.append(
            f"  const spa = window.XaniaSPA.createApp({{ rootId: {_js_string(app.root_id)}, apiBase: {_js_string(app.api_base)}, scrollRestoration: 'top' }});"
        )
        lines.append("")
        # Helper available to pages for safe escaping.
        lines.append("  function escapeHtml(value) {")
        lines.append("    return String(value)")
        lines.append("      .replaceAll('&', '&amp;')")
        lines.append("      .replaceAll('<', '&lt;')")
        lines.append("      .replaceAll('>', '&gt;')")
        lines.append('      .replaceAll(\'\"\', "&quot;")')
        lines.append("      .replaceAll(\"'\", '&#39;');")
        lines.append("  }")
        lines.append("")

        for r in app.routes:
            title = getattr(r.page, "title", "Page")
            lines.append(f"  spa.route({_js_string(r.path)}, (ctx) => {{")
            # Provide `escapeHtml` to template pages via ctx.escapeHtml.
            lines.append("    ctx.escapeHtml = escapeHtml;")
            lines.append(f"    const title = {_js_string(title)};")
            lines.append(f"    const html = {r.page.render_js('ctx')};")
            lines.append("    return (")
            lines.append("      '<div class=\"max-w-5xl mx-auto px-4 md:px-8 py-10\">' +")
            lines.append(
                "      '<div class=\"mb-6\"><div class=\"text-3xl font-black\">' + escapeHtml(title) + '</div></div>' +"
            )
            lines.append("      html +")
            lines.append("      '</div>'")
            lines.append("    );")
            lines.append("  });")
            lines.append("")

        lines.append("  spa.start();")
        lines.append("})();")
        lines.append("")
        return "\n".join(lines)
